service: kittenDB

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan*
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-kittens-${opt:stage}

  environment:
      DYNAMODB_KITTEN_TABLE: ${self:service}-kittens-${opt:stage}

resources:
  Resources:
    kittensTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:service}-kittens-${opt:stage}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
  create:
    handler: handler.create
    events:
      - http:
          path: /v1/kitten
          method: post
  list:
    handler: handler.list
    events:
      - http:
          path: /v1/kitten
          method: get
  get:
    handler: handler.get
    events:
      - http:
          path: /v1/kitten/{name}
          method: get
  update:
    handler: handler.update
    events:
      - http:
          path: /v1/kitten/{name}
          method: put
  delete:
    handler: handler.delete
    events:
      - http:
          path: /v1/kitten/{name}
          method: delete