# NOTE: This file is for VSCode with the "REST Client" extension to call the endpoints
# Change xxx for your urls in the "endpoints" output of sls deploy

POST https://xxx.execute-api.us-east-1.amazonaws.com/dev/hello

### Create
POST https://xxx.execute-api.us-east-1.amazonaws.com/dev/v1/kitten

{"name":"Fluffy", "age":4}

### Scan
GET https://xxx.execute-api.us-east-1.amazonaws.com/dev/v1/kitten

### Get
GET https://xxx.execute-api.us-east-1.amazonaws.com/dev/v1/kitten/Fluffy

### Update
PUT https://xxx.execute-api.us-east-1.amazonaws.com/dev/v1/kitten/Fluffy

{"age":5}

### Delete
DELETE https://xxx.execute-api.us-east-1.amazonaws.com/dev/v1/kitten/Fluffy


